version: 2.1

jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Running Tests
          command: npm test

#         #...
# jobs:
#   build:
#     docker:
#       - image: <image-name-tag>
#     steps:
#       - checkout # Special step to checkout your source code
#       - run: # Run step to execute commands, see
#       # circleci.com/docs/2.0/configuration-reference/#run
#           name: Running tests
#           command: make test # executable command run in
#           # non-login shell with /bin/bash -eo pipefail option
#           # by default.
# #...          
