version: 2.1

executors:
  docker-executor:
    docker:
      - image: node:14

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm install
  test:
    executor: docker-executor
    steps:
      - run:
          name: Running Tests
          command: npm test

workflows:
  build:
    jobs:
      - build
  test:
    jobs:
      - build
      - test:
          requires:
          - build
# jobs:
#   build:
#     docker:
#       - image: <image-name-tag>
#     steps:
#       - checkout # Special step to checkout your source code
#       - run: # Run step to execute commands, see
#       # circleci.com/docs/2.0/configuration-reference/#run
#           name: Running tests
#           command: make test # executable command run in
#           # non-login shell with /bin/bash -eo pipefail option
#           # by default.
# #...          
