version: 2.1
commands:
  install:
    steps:
      - checkout
      - run: npm install
  build:
    steps:
      - install
      - run: npm build
  run:
    steps:
      - install
      - run: npm start

executors:
  docker-executor:
    docker:
      - image: node:alpine

jobs:
  start-jobs:
    executor: docker-executor
    steps:
      - install

workflow:
  install:
    jobs:
      - start-jobs
