version: 2.1
commands:
  install:
    steps:
      - checkout
      - run: npm install
  build:
    steps:
      - install
      - run: npm build
  build-docker-image:
    steps:
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME
  deploy-to-docker-hub:
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $IMAGE_NAME

  test:
    steps:
      - install
      - run: npm test
  start:
    steps:
      - install
      - run: npm start

executors:
  docker-executor:
    docker:
      - image: node:14

jobs:
  start-jobs:
    executor: docker-executor
    steps:
      - install
  build:
    executor: docker-executor
    steps:
      - install
  build-docker-image:
    executor: docker-executor
    working_directory: /usr/src/app
    environment:
      IMAGE_NAME: fredericor/initial:node-test-from-circleci
    steps:
      - install
      - build-docker-image
  deploy-to-docker-hub:
    executor: docker-executor
    working_directory: /usr/src/app
    environment:
      IMAGE_NAME: fredericor/initial:node-test-from-circleci
    steps:
      - deploy-to-docker-hub
  test:
    executor: docker-executor
    steps:
      - run: npm test
      - store_test_results:
          path: ./test-results/jest/
  start:
    executor: docker-executor
    steps:
      # - install
      - test
      - start

workflows:
  installation:
    jobs:
      - build
      - start:
          requires:
            - build
          filters:
            branches:
              only: master
  build-and-deploy:
    jobs:
      - build-docker-image
      - deploy-to-docker-hub:
          requires:
            - build-docker-image
          