version: 2.1
commands:
  install:
    steps:
      - checkout
      - run: npm install
  build:
    steps:
      - install
      - run: npm build
  test:
    steps:
      - install
      - run: npm test
  start:
    steps:
      - install
      - run: npm start

executors:
  docker-executor:
    docker:
      - image: node:14

jobs:
  start-jobs:
    executor: docker-executor
    steps:
      - install
  build:
    executor: docker-executor
    steps:
      - install
  test:
    executor: docker-executor
    steps:
      - run: npm test
      - store_test_results:
          path: ./test-results/jest/
  start:
    executor: docker-executor
    steps:
      # - install
      - test
      - start

workflows:
  installation:
    jobs:
      # - start-jobs
      - build
      - start:
          requires:
            - build
          filters:
            branches:
              only: master
          